const { contextBridge, ipcRenderer, webUtils } = require('electron');

const invoke = (channel, ...args) => ipcRenderer.invoke(channel, ...args);

contextBridge.exposeInMainWorld('launcher', {
  platform: process.platform,
  getSettings: () => invoke('settings:get'),
  saveSettings: (patch) => invoke('settings:save', patch),
  setPopupOpen: (open) => invoke('window:popup', open),
  pickJava: () => invoke('settings:pickJava'),
  getAppInfo: () => invoke('app:info'),
  openLauncherFolder: () => invoke('app:openFolder'),
  checkForUpdate: () => invoke('update:check'),
  updateInstance: (id, patch) => invoke('instances:update', id, patch),
  listVersions: () => invoke('versions:list'),

  listAccounts: () => invoke('accounts:list'),
  refreshProfiles: () => invoke('accounts:refreshProfiles'),
  selectAccount: (id) => invoke('accounts:select', id),
  removeAccount: (id) => invoke('accounts:remove', id),
  addOfflineAccount: (name) => invoke('accounts:addOffline', name),
  openSkins: (accountId) => invoke('skins:open', accountId),
  addSkins: () => invoke('skins:add'),
  addDroppedSkins: (files) => invoke('skins:addDropped', files),
  fontSheet: () => invoke('skins:font'),
  removeSkin: (skinId) => invoke('skins:remove', skinId),
  applySkin: (accountId, choice) => invoke('skins:apply', accountId, choice),

  listSchematics: () => invoke('schematics:list'),
  loadSchematic: (file, cells, budget) => invoke('schematics:load', file, cells, budget),
  onSchematicProgress: (fn) => ipcRenderer.on('schematics:progress', (_event, file, fraction) => fn(file, fraction)),
  blockAssets: () => invoke('schematics:blocks'),
  saveSchematicPreview: (file, dataUrl, info) => invoke('schematics:savePreview', file, dataUrl, info),
  revealSchematic: (file) => invoke('schematics:reveal', file),
  openSchematicsFolder: (parts) => invoke('schematics:openFolder', parts),
  trashSchematics: (files, folders) => invoke('schematics:trash', files, folders),
  groupSchematics: (files, name, parent) => invoke('schematics:group', files, name, parent),
  schematicGroups: (parent) => invoke('schematics:groups', parent),
  renameSchematic: (file, name) => invoke('schematics:rename', file, name),
  moveSchematics: (files, folders, target) => invoke('schematics:move', files, folders, target),
  renameSchematicFolder: (parts, name) => invoke('schematics:renameFolder', parts, name),
  newSchematicFolder: (parent, name) => invoke('schematics:newFolder', parent, name),
  importSchematics: (files, parent) => invoke('schematics:import', files, parent),
  loginStart: () => invoke('accounts:loginStart'),
  loginFinish: () => invoke('accounts:loginFinish'),
  loginCancel: () => invoke('accounts:loginCancel'),
  copyCodeAndOpen: (code, url) => invoke('accounts:copyCodeAndOpen', code, url),

  listInstances: () => invoke('instances:list'),
  createInstance: (options) => invoke('instances:create', options),
  reorderInstances: (ids) => invoke('instances:reorder', ids),
  deleteInstance: (id) => invoke('instances:delete', id),
  openFolder: (id) => invoke('instances:openFolder', id),
  setSync: (id, item, enabled) => invoke('instances:setSync', id, item, enabled),
  setInstanceIcon: (id, name) => invoke('instances:setIcon', id, name),
  setServerIcon: (id, name) => invoke('servers:setIcon', id, name),
  listIcons: () => invoke('icons:list'),
  launch: (id) => invoke('instances:launch', id),

  listContent: (id) => invoke('content:list', id),
  watchContent: (id) => invoke('content:watch', id),
  onContentChanged: (callback) => ipcRenderer.on('content-changed', (_event, id) => callback(id)),
  addModFiles: (id, files) => invoke('mods:addFiles', id, files.map((file) => webUtils.getPathForFile(file))),
  removeContent: (id, type, file) => invoke('content:remove', id, type, file),
  setModEnabled: (id, file, enabled) => invoke('mods:setEnabled', id, file, enabled),
  checkModUpdates: (id) => invoke('mods:updates', id),
  listModVersions: (id, file) => invoke('mods:versions', id, file),
  setModVersion: (id, file, versionId) => invoke('mods:setVersion', id, file, versionId),
  search: (id, query, type, offset) => invoke('modrinth:search', id, query, type, offset),
  install: (id, projectId, type) => invoke('modrinth:install', id, projectId, type),
  searchModpacks: (query, offset) => invoke('modpacks:search', query, offset),
  modpackGameVersions: (projectId) => invoke('modpacks:gameVersions', projectId),
  installModpack: (projectId, name, versionId) => invoke('modpacks:install', projectId, name, versionId),
  pickModpackFile: () => invoke('modpacks:pickFile'),
  dropModpackFile: (file) => invoke('modpacks:dropFile', webUtils.getPathForFile(file)),
  installModpackFile: (name, trust) => invoke('modpacks:installFile', name, trust),
  openExternal: (url) => invoke('openExternal', url),

  listServers: () => invoke('servers:list'),
  reorderServers: (ids) => invoke('servers:reorder', ids),
  addServer: () => invoke('servers:add'),
  listServerVersions: (type) => invoke('servers:versions', type),
  serverOnline: (id) => invoke('servers:online', id),
  restartServer: (id) => invoke('servers:restart', id),
  serverProperties: (id) => invoke('servers:properties', id),
  setServerProperties: (id, changes) => invoke('servers:setProperties', id, changes),
  serverFiles: (id) => invoke('servers:files', id),
  readServerFile: (id, file) => invoke('servers:readFile', id, file),
  writeServerFile: (id, file, text, modified) => invoke('servers:writeFile', id, file, text, modified),
  setServerPublic: (id, on) => invoke('servers:setPublic', id, on),
  whitelistAdd: (id, name) => invoke('servers:whitelistAdd', id, name),
  whitelistRemove: (id, name) => invoke('servers:whitelistRemove', id, name),
  playitStatus: () => invoke('playit:status'),
  playitLinkStart: () => invoke('playit:linkStart'),
  playitLinkFinish: () => invoke('playit:linkFinish'),
  playitLinkCancel: () => invoke('playit:linkCancel'),
  playitUnlink: () => invoke('playit:unlink'),
  createServer: (options) => invoke('servers:create', options),
  removeServer: (id) => invoke('servers:remove', id),
  openServerFolder: (id) => invoke('servers:openFolder', id),
  startServer: (id) => invoke('servers:start', id),
  stopServer: (id) => invoke('servers:stop', id),
  serverCommand: (id, text) => invoke('servers:command', id, text),
  joinServer: (id, instanceId) => invoke('servers:join', id, instanceId),

  stopServersAndClose: () => invoke('app:stopServersAndClose'),
  onCloseRequested: (callback) => ipcRenderer.on('close-requested', (_event, names) => callback(names)),
  getUpdate: () => invoke('update:get'),
  installUpdate: () => invoke('update:install'),
  onUpdate: (callback) => ipcRenderer.on('update', (_event, data) => callback(data)),

  onStatus: (callback) => ipcRenderer.on('status', (_event, data) => callback(data)),
  onNavigate: (callback) => ipcRenderer.on('navigate', (_event, direction) => callback(direction)),
  onLog: (callback) => ipcRenderer.on('log', (_event, data) => callback(data)),
  onServerStatus: (callback) => ipcRenderer.on('server-status', (_event, data) => callback(data)),
  onServerLog: (callback) => ipcRenderer.on('server-log', (_event, data) => callback(data)),
  onServerOnline: (callback) => ipcRenderer.on('server-online', (_event, data) => callback(data)),
});
