const { contextBridge, ipcRenderer } = require('electron');

const invoke = (channel, ...args) => ipcRenderer.invoke(channel, ...args);

contextBridge.exposeInMainWorld('launcher', {
  getSettings: () => invoke('settings:get'),
  saveSettings: (patch) => invoke('settings:save', patch),
  listVersions: () => invoke('versions:list'),

  listAccounts: () => invoke('accounts:list'),
  refreshProfiles: () => invoke('accounts:refreshProfiles'),
  selectAccount: (id) => invoke('accounts:select', id),
  removeAccount: (id) => invoke('accounts:remove', id),
  addOfflineAccount: (name) => invoke('accounts:addOffline', name),
  loginStart: () => invoke('accounts:loginStart'),
  loginFinish: () => invoke('accounts:loginFinish'),
  loginCancel: () => invoke('accounts:loginCancel'),
  copyCodeAndOpen: (code, url) => invoke('accounts:copyCodeAndOpen', code, url),

  listInstances: () => invoke('instances:list'),
  createInstance: (options) => invoke('instances:create', options),
  deleteInstance: (id) => invoke('instances:delete', id),
  openFolder: (id) => invoke('instances:openFolder', id),
  setSync: (id, item, enabled) => invoke('instances:setSync', id, item, enabled),
  launch: (id) => invoke('instances:launch', id),

  listMods: (id) => invoke('mods:list', id),
  removeMod: (id, file) => invoke('mods:remove', id, file),
  listModVersions: (id, file) => invoke('mods:versions', id, file),
  setModVersion: (id, file, versionId) => invoke('mods:setVersion', id, file, versionId),
  search: (id, query, type, offset) => invoke('modrinth:search', id, query, type, offset),
  install: (id, projectId, type) => invoke('modrinth:install', id, projectId, type),
  openExternal: (url) => invoke('openExternal', url),

  listServers: () => invoke('servers:list'),
  addServer: () => invoke('servers:add'),
  listServerVersions: (type) => invoke('servers:versions', type),
  serverOnline: (id) => invoke('servers:online', id),
  restartServer: (id) => invoke('servers:restart', id),
  serverProperties: (id) => invoke('servers:properties', id),
  setServerProperties: (id, changes) => invoke('servers:setProperties', id, changes),
  serverFiles: (id) => invoke('servers:files', id),
  readServerFile: (id, file) => invoke('servers:readFile', id, file),
  writeServerFile: (id, file, text, modified) => invoke('servers:writeFile', id, file, text, modified),
  setServerPublic: (id, on) => invoke('servers:setPublic', id, on),
  whitelistAdd: (id, name) => invoke('servers:whitelistAdd', id, name),
  whitelistRemove: (id, name) => invoke('servers:whitelistRemove', id, name),
  playitStatus: () => invoke('playit:status'),
  playitLinkStart: () => invoke('playit:linkStart'),
  playitLinkFinish: () => invoke('playit:linkFinish'),
  playitLinkCancel: () => invoke('playit:linkCancel'),
  playitUnlink: () => invoke('playit:unlink'),
  createServer: (options) => invoke('servers:create', options),
  removeServer: (id) => invoke('servers:remove', id),
  openServerFolder: (id) => invoke('servers:openFolder', id),
  startServer: (id) => invoke('servers:start', id),
  stopServer: (id) => invoke('servers:stop', id),
  serverCommand: (id, text) => invoke('servers:command', id, text),
  joinServer: (id, instanceId) => invoke('servers:join', id, instanceId),

  getVersion: () => invoke('app:version'),
  stopServersAndClose: () => invoke('app:stopServersAndClose'),
  onCloseRequested: (callback) => ipcRenderer.on('close-requested', (_event, names) => callback(names)),
  getUpdate: () => invoke('update:get'),
  installUpdate: () => invoke('update:install'),
  onUpdate: (callback) => ipcRenderer.on('update', (_event, data) => callback(data)),

  onStatus: (callback) => ipcRenderer.on('status', (_event, data) => callback(data)),
  onLog: (callback) => ipcRenderer.on('log', (_event, data) => callback(data)),
  onServerStatus: (callback) => ipcRenderer.on('server-status', (_event, data) => callback(data)),
  onServerLog: (callback) => ipcRenderer.on('server-log', (_event, data) => callback(data)),
  onServerOnline: (callback) => ipcRenderer.on('server-online', (_event, data) => callback(data)),
});
